/*
 * @Descripttion: 
 * @version: 
 * @Author: xiaoshuyui
 * @email: guchengxi1994@qq.com
 * @Date: 2022-05-19 19:18:31
 * @LastEditors: xiaoshuyui
 * @LastEditTime: 2022-05-19 19:18:31
 */
const String fileTitle = """
import 'package:flutter/material.dart';

/// generated by taichi
///
/// please modify if you want to

""";
