name: taichi_casbin

homepage: https://github.com/guchengxi1994/taichi

version: 0.0.1 # dev1

environment: 
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  ini: ^2.1.0
  tuple: ^2.0.0

dev_dependencies:
  lint: ^1.8.2