name: taichi_auth  

introduction: an open-source access control library, inspired by casbin ,written in dart

homepage: https://github.com/guchengxi1994/taichi

version: 0.0.3 # dev3

environment: 
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  csv: ^5.0.1
  equatable: ^2.0.3
  glob: ^2.0.2
  ini: ^2.1.0
  synchronized: ^3.0.0+2
  tuple: ^2.0.0

dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.1
