name: taichi_valuate 

introduction: valuate from strings

homepage: https://github.com/guchengxi1994/taichi

version: 0.0.1 # dev1

environment: 
  sdk: ">=2.16.2 <3.0.0"

dependencies: 
  lpinyin: ^2.0.2
  tuple: ^2.0.0


dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.1