name: taichi_file_manager
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.4

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_simple_treeview: ^3.0.1
  taichi:
    path: ../../taichi_core
    # git:
    #     url: https://github.com/guchengxi1994/taichi
    #     ref: dev
    #     path: taichi_core
  dio: 4.0.6
  fluttertoast: ^8.0.9
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


deferred-components:
  - name: file_manager
    libraries:
      - package:taichi_file_manager/widgets/sidemenu.dart
      - package:taichi_file_manager/widgets/appbar.dart
      - package:taichi_file_manager/widgets/main_screen_body.dart


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

