name: taichi_admin
description: 一个flutter做的管理平台模板。 A flutter admin templete.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  file_picker: ^4.6.1
  pie_chart: ^5.3.1
  shimmer: ^2.0.0


  taichi:
    # path: D:/github_repo/taichi/taichi_core
    git:
        url: https://github.com/guchengxi1994/taichi
        ref: dev
        path: taichi_core
  taichi_china_map:
    # path: ../taichi_china_map
    git:
        url: https://github.com/guchengxi1994/taichi
        ref: dev
        path: taichi_china_map
  
  taichi_accessible_widget:
    path: ../taichi_accessible_widget
    # git:
    #     url: https://github.com/guchengxi1994/taichi
    #     ref: dev
    #     path: taichi_china_map



deferred-components:
  - name: taichi_admin_widgets
    libraries:
      - package:taichi_admin/screens/main_screen.dart
      - package:taichi_admin/screens/dashboard.dart
      - package:taichi_admin/screens/from_screens/first_screen.dart
      - package:taichi_admin/screens/from_screens/second_screen.dart
      - package:taichi_admin/screens/reserved_screen.dart
      - package:taichi_admin/widgets/dashboard_custom_card.dart
      - package:taichi_admin/widgets/dashboard_custom_pie_chart.dart
      - package:taichi_admin/widgets/dashboard_left_part.dart
      - package:taichi_admin/widgets/dashboard_right_part.dart
      - package:taichi_admin/widgets/side_menu.dart
      - package:taichi_admin/widgets/side_menu_header.dart
      - package:taichi_admin/widgets/appbar.dart
      - package:taichi_admin/widgets/appbar_dropdown_button.dart
      - package:taichi_admin/widgets/appbar_search.dart
      - package:taichi_admin/widgets/form_1.dart
      - package:taichi_admin/widgets/form_2.dart
      - package:taichi_admin/widgets/table_widget.dart
      - package:taichi_china_map/lib.dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/demo.png
    - assets/images/0.jpg
    - assets/role.yaml
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
