// ignore: unused_import
import 'package:flutter/material.dart';

/*
  使用 {name} 替换 class 的名字，
  由于是 Stack, 所以只要关注children的绝对定位即可
*/

const String stackStatelessTempleteCode = """
import 'package:flutter/material.dart';

/// generated by taichi
///
/// please modify if you want to
class {name} extends StatelessWidget {
  const {name}({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: {children},
    );
  }
}
""";
