name: taichi_access_widget
description: use a config file to determine if widgets are accessible

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  taichi:
    git:
        url: https://github.com/guchengxi1994/taichi
        ref: dev
        path: taichi_valuate

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


